#!/bin/tcsh
#PBS -N runupload
#PBS -l nodes=1:vortex:ppn=12
#PBS -l walltime=1:00:00
#PBS -j oe
#PBS -o /sciclone/geounder/dev/geoBoundaries/scripts/geoBoundaryBot/external/DataVerse/jobFiles


source "/usr/local/anaconda3-2021.05/etc/profile.d/conda.csh"
module load anaconda3/2021.05
module load python/usermodules
module load git/2.9.5
module load git-lfs/3.2.0

unsetenv PYTHONPATH

conda activate hdx
cd /sciclone/geounder/dev/geoBoundaries/scripts/geoBoundaryBot/external/DataVerse
python uploadFiles.py vortex >& uploadFiles.out
